name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version-file: 'go.mod'
      - name: Install Task
        run: |
          sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d -b ~/.local/bin
      
      - name: Install protoc
        run: |
          sudo apt-get update
          sudo apt-get install -y protobuf-compiler

      - name: Install sqlc
        run: |
          curl -L https://github.com/sqlc-dev/sqlc/releases/download/v1.27.0/sqlc_1.27.0_linux_amd64.tar.gz -o sqlc.tar.gz
          tar -xzf sqlc.tar.gz
          sudo mv sqlc /usr/local/bin/
          sqlc version
      
      - name: Download Go modules
        run: go mod download

      - name: Generate gRPC files
        run: ~/.local/bin/task generate
      
      - name: Generate SQLC files
        run: ~/.local/bin/task gen:sql

      - name: Test
        run: go test -v ./...
      - name: Build
        run: go build -o ./bin/ -v ./...

      - name: Upload generated files
        uses: actions/upload-artifact@v4
        with:
          name: generated-files
          path: |
            pkg/chat_v1/
            internal/db/
          retention-days: 1
    # uses: mihailtudos/actions/.github/workflows/go-ci.yml@v1.0.3
  deploy:
    needs: test-and-build
    # if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    # uses: mihailtudos/actions/.github/workflows/go-cd.yml@v1.0.3
    # secrets: inherit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Upload Docker compose files
        run: |
            rsync -avz \
            docker-compose.yml \
            docker-compose.prod.yml \
            Taskfile.yml \
            ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }}:/home/${{ secrets.REMOTE_USER }}/chat

      - name: Deploy to Server via SSH
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          envs: GOOSE_DBSTRING,GOOSE_DRIVER,PORT
          script: |
            cd /home/${{ secrets.REMOTE_USER }}/chat
            echo "GOOSE_DBSTRING=\"$GOOSE_DBSTRING\"" > .env.prod
            echo "GOOSE_DRIVER=$GOOSE_DRIVER" >> .env.prod
            echo "PORT=$PORT" >> .env.prod

            ENV=prod task docker:prod:up
        env:
          GOOSE_DBSTRING: ${{ secrets.GOOSE_DBSTRING }}
          GOOSE_DRIVER: ${{ secrets.GOOSE_DRIVER }}
          PORT: ${{ secrets.PORT }}