name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        
      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version-file: 'go.mod'

      - name: Setup Task
        uses: arduino/setup-task@v1
        with:
          version: 3.x
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Download Go modules
        run: go mod download
      
      - name: Generate grpc and sqcl files
        run: task generate

      - name: Test
        run: task test

      - name: Build
        run: task build:app

      - name: Upload generated files
        uses: actions/upload-artifact@v4
        with:
          name: generated-files
          path: |
            pkg/chat_v1/
            internal/db/
          retention-days: 1
  push-image:
    needs: test-and-build
    # if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Download generated code
        uses: actions/download-artifact@v7
        with: 
          name: generated-files
      
      - name: Setup Task
        uses: arduino/setup-task@v1
        with:
          version: 3.x
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        run: task docker:push

  deploy:
    needs: [test-and-build, push-image]
    # if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Copy docker-compose.yml to server
        uses: appleboy/scp-action@master
        with:
            host: ${{ secrets.REMOTE_HOST }}
            username: ${{ secrets.REMOTE_USER }}
            key: ${{ secrets.SSH_PRIVATE_KEY }}
            source: "docker-compose.yml,docker-compose.prod.yml,Taskfile.yml"
            target: "/home/${{ secrets.REMOTE_USER }}/chat"

      - name: Deploy to Server via SSH
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          envs: GOOSE_DBSTRING,GOOSE_DRIVER,PORT
          script: |
            cd /home/${{ secrets.REMOTE_USER }}/chat
            echo "GOOSE_DBSTRING=\"$GOOSE_DBSTRING\"" > .env.prod
            echo "GOOSE_DRIVER=$GOOSE_DRIVER" >> .env.prod
            echo "PORT=$PORT" >> .env.prod

            ENV=prod task docker:prod:up
        env:
          GOOSE_DBSTRING: ${{ secrets.GOOSE_DBSTRING }}
          GOOSE_DRIVER: ${{ secrets.GOOSE_DRIVER }}
          PORT: ${{ secrets.PORT }}